### PR TITLE
Make `w`, `W`, `e`, `E`, `b` and `B` in normal and select mode behave exactly like Vim

### LINKED ISSUE #44: Word motion slightly different from vim
### Summary

In vim or neovim, when the cursor is on whitespace and I press `w`, the cursor moves to the start of the next word. In evil-helix, it skips one word.

### Reproduction Steps

 

I tried this:

In the following text,

```
abc def
 foo bar.
```

If my cursor is on the space on the second line and I press `w`, the cursor moves to the "b" in "bar".

I expected that it would move to the "f" in "foo".

### Helix log

_No response_

### Platform

macOS

### Terminal Emulator

iTerm2

### Installation Method

source

### Helix Version

evil-helix release-20240716 (a2c8565c, helix 24.7)

### PR DESCRIPTION
**Pull request by thomie**
This pull request fixes the following bugs:

Commit 1:
* In select mode, the key sequence `wb` would result in a selection,
   instead of being a no-op as in Vim.

* The functions `evil_next_word_end` and `evil_next_long_word_end`
   (mapped to 'e' and 'E') in normal mode would make the cursor land on
   the space after the word, instead of the last character of the word.

Commit 2:
* Space before word: when the cursor is on the space before a word, and
   you hit `w`, Vim will move the cursor to this word, but evil-helix
   would skip the word and move to the _next_ word.

* Punctuation: when the cursor is on the letter 'f' in "foo.bar qux",
   and you hit `w` twice, Vim will move the cursor to the letter 'b',
   but evil-helix would skip to the letter 'q'.

   This bug has the same underlying cause as the previous one, and the
   fix for both is to move the cursor one character to the left before
   doing the word move.

* Newlines: when the cursor is on the 'f' in "foo\nbar", and you hit
   `w`, Vim will move the cursor to the letter 'b' (so to the next
   line), but evil-helix would move the cursor onto the newline
   character. See the changes in `reached_target` for the fix.

With this pull request, evil-helix passes all the tests defined here: https://github.com/thomie/vim-keymap-test/blob/a50b737fa75f44af84378f4e2d59be4da67bdd7b/word-motions.test. 

Closes https://github.com/usagi-flow/evil-helix/issues/44

### CODE REVIEW

File: helix-core/src/movement.rs [hunk 1]
```diff
@@ -555,6 +558,14 @@ fn reached_target(target: WordMotionTarget, prev_ch: char, next_ch: char) -> boo
             is_sub_word_boundary(prev_ch, next_ch, Direction::Backward)
                 && (!(prev_ch.is_whitespace() || prev_ch == '_') || char_is_line_ending(next_ch))
         }
+        WordMotionTarget::EvilNextWordStart => {
+            is_word_boundary(prev_ch, next_ch)
+                && (!char_is_line_ending(next_ch) && !next_ch.is_whitespace())
```
Comment (thomie) [inline helix-core/src/movement.rs:563]: Hello @usagi-flow, I introduced this bit of evil specific code here, which might make rebasing/merging with upstream harder in the future.

Perhaps it's possible to get rid of it, at the expense of complicating the code in `commands/evil.rs` a bit more, though I haven't tried. Let me know what you prefer.

Comment (usagi-flow) [reply helix-core/src/movement.rs:563]: Thank you for asking. I think this is a fine, pragmatic approach; and still simple enough to be quickly understood, should a conflict arise in the future.

I'll work with this branch for a while if I can, to manually test it a bit.

Thank you very much for this PR!

**Review by usagi-flow — APPROVED** [review]
Thanks again for this PR! I tried it out, and the behavior is exactly as expected (i.e. as in Vim). I'm getting this merged and I'll prepare a release in the next few days.

**Comment by thomie** [comment]
Thanks for the merge!
